name: publish

on:
  release:
    types: [created]

jobs:
  publish-python-package:
    uses: JovialKnoll/workflows/.github/workflows/publish-python-package.yml@master
    needs: test-python
    with:
      python_version: '3.10'
      actual_publish: true
    secrets:
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
