name: release

on:
  push:
    tags:
      - v*.*.*

jobs:
  test-python:
    uses: JovialKnoll/workflows/.github/workflows/test-python.yml@master
    with:
      python_version: '3.12'

  publish-python-package:
    uses: JovialKnoll/workflows/.github/workflows/publish-python-package.yml@master
    needs: test-python
    with:
      python_version: '3.12'
    secrets:
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

  create-release:
    uses: JovialKnoll/workflows/.github/workflows/create-release.yml@master
    needs: publish-python-package
