name: test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  test-python:
    uses: JovialKnoll/workflows/.github/workflows/test-python.yml@master
    with:
      python_version: '3.10'
